export const LOAD_PROFILE_DATA = 'LOAD_PROFILE_DATA'

export const LOGIN_USER = 'LOGIN_USER'
export const REGISTRATION_USER = 'REGISTRATION_USER'
export const REGISTRATION_AGREEMENTS = 'REGISTRATION_AGREEMENTS'
export const LOGOUT = 'LOGOUT'
